package(default_visibility = ["//visibility:public"])

cc_library(
    name = "game_cc",
    srcs = ["game.cc"],
    hdrs = ["game.h"],
    deps = [
        "//entities:player_cc",
        "@sdl2",
    ],
)
