package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "bullet_hell_main",
    srcs = ["bullet_hell_main.cc"],
    deps = [
        "//game:game",
        "@com_google_absl//absl/flags:flag",
    ],
)
