package(default_visibility = ["//level:__subpackages__"])

filegroup(
    name = "level_graph_txt",
    srcs = ["level_graph.txt"],
)

filegroup(
    name = "tiles",
    srcs = glob(["tiles/*"]),
)

filegroup(
    name = "room_tile_map_txt",
    srcs = ["room_tile_map.txt"],
)
